apiVersion: v1
kind: Service
metadata:
  name: neuroclaim-db
  namespace: neuroclaim
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: neuroclaim
    tier: backend
