apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroclaim-db
  namespace: neuroclaim
  labels:
    name: neuroclaim-db
    tier: backend 
spec:
  selector:
    matchLabels:
        app: neuroclaim
        tier: backend      
  replicas: 1
  template:
    metadata: 
      name: db
      labels:
        app: neuroclaim
        tier: backend

    spec:
      containers:
        - name: neuroclaim-db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_USER
          volumeMounts:
            - name: init-data
              mountPath: /docker-entrypoint-initdb.d
            - name: sqldata
              mountPath: /var/lib/mysql
      volumes:
      - name: init-data
        configMap:
          name: db-configmap
      - name: sqldata
        persistentVolumeClaim:
            claimName: db-pvc-1gb