apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    name: myapp-deploy
    tyre: fronend
spec:
  selector:
    matchLabels:
      app: medicalcoder
      tier: front-end
  replicas: 2
  template:
    metadata:
      name: up
      labels:
        app: medicalcoder
        tier: front-end
    spec:
      containers:
        - name: medicalcoder
          image: docker.io/mrafit20/medicalcoder:1.0.2 # {"$imagepolicy": "flux-system:medicalcodeimagepolicy"}
          ports:
            - containerPort: 5000
