apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroclaim-ui
  namespace: neuroclaim
  labels:
    app: neuroclaim
    component: ui
spec:
  selector:
    matchLabels:
      app: neuroclaim
      component: ui
  replicas: 2
  template:
    metadata:
      labels:
        app: neuroclaim
        component: ui
    spec:
      containers:
        - name: neuroclaim-ui
          image: neuroclaim:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: neuroclaim-db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
