apiVersion: v1
kind: Service
metadata:
  name: claimbot-ui
  namespace: claimbot
spec:
  selector:
    app: claimbot
    component: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
